### ISSUE TITLE
OBO Library PURL metadata record incorrect for versionIRI

### ISSUE THREAD

**Issue by hlapp** [evoinfo/miapa#27]
The canonical IRI for the MIAPA ontology (<http://purl.obolibrary.org/obo/miapa.owl>) resolves, but its versionIRI (<http://purl.obolibrary.org/obo/miapa/2013-02-01/miapa.owl>) does not.

Until now, this was in part because there was no release tag or other mechanism for accessing that specific version, but [I have created one now](https://github.com/evoinfo/miapa/releases/tag/2013-02-01). This means that the same URL pattern that is used for the canonical IRI should work for the version IRI simply by replacing `master` with the version (`2013-02-01` in this case). This mechanism needs to be coded into the [miapa.owl metadata record for the OBO Library PURL resolution](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/miapa.yml).

**Comment by hlapp** [comment]
@balhoff gave [an example for how this is implemented](https://github.com/evoinfo/cdao/issues/1#issuecomment-299535526) for another ontology (tax rank)

**Comment by hlapp** [comment]
I think the documentation for what we need is [here](https://github.com/OBOFoundry/purl.obolibrary.org#entries). 

If I understand this right we have different options:
1. Use `prefix`, one (`/`) as fallback for the canonical, and perhaps `/20` for matching release versions (at least until 2099 😄 ).
2. Use `exact`, one for each release prefix (i.e., for now `/2013-02-01/`). I don't expect many releases, so this could well be workable, at least for the time being.
3. Use `regex`, with `/\d{4}-\d{2}-\d{2}` or something like that. The documentation advises against that (not sure why - we all _love_ regular expressions, no 😏).

@cmungall or @balhoff any thoughts here as to which one is best to try first? I'm leaning to (2).

**Comment by cmungall** [comment]
Another option is to change the scheme moving forward to use /releases/, and have hardcoded entries for all previous releases

**Comment by balhoff** [comment]
Good idea.

**Comment by hlapp** [comment]
Yay, works now.

Note to self - closing Github issues across organizations through recognized phrases does not work (and arguably, on second thought, maybe indeed shouldn't 😄
